name: Full Stack CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  backend:
    name: Build and Test Backend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.x'

    - name: Restore .NET dependencies
      run: dotnet restore ./backend/new-inf-tech-1-back.csproj

    - name: Build .NET project
      run: dotnet build --no-restore ./backend/new-inf-tech-1-back.csproj

    - name: Test .NET project
      run: dotnet test --no-restore --verbosity normal ./backend/new-inf-tech-1-back.csproj

  frontend:
    name: Build and Test Frontend
    runs-on: ubuntu-latest
    needs: backend  # Зависит от выполнения backend job

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install

    - name: Run frontend tests
      run: |
        cd frontend
        npm test

    - name: Build frontend
      run: |
        cd frontend
        npm run build
